In [27]:
import os

import tensorflow as tf
from tensorflow import keras

import tensorflow_hub as hub
import numpy as np
import numpy
import pandas as pd
import pickle
import os
import pathlib

from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions
from tensorflow.keras.preprocessing import image# Helper libraries
import matplotlib.pyplot as pl

In [28]:
tf.get_logger().setLevel('ERROR')

In [29]:
# Load image dataset
dataset_path = "../../data/80apples/"
data_dir = pathlib.Path(dataset_path)
apple_images = list()

In [30]:
for filename in os.listdir(dataset_path):
    imgAppleDirectory = os.path.join(dataset_path)
    apple_images.append(imgAppleDirectory)
    # print(apple_images)
    
apple_images = [img for img in apple_images if ".jpg" in img]
print(type(apple_images))

<class 'list'>


In [31]:
# img = image.load_img(apple_images, target_size=(224, 224))
img_size = (224, 224)
batch_size= 32

In [32]:
apple_images = tf.keras.utils.image_dataset_from_directory(
  data_dir,
  image_size=img_size,
  batch_size=batch_size)

Found 80 files belonging to 1 classes.


In [33]:
# Loadmodel
model = tf.keras.models.load_model('../saved_models/tl_mobileNetV2/model/tl_22112022_12h10_1.h5', custom_objects=None, compile=True, options=None)
classifier = tf.keras.Sequential([
    hub.KerasLayer("https://tfhub.dev/google/tf2-preview/mobilenet_v2/classification/4", input_shape=img_size+(3,))
])
# Show the model
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 sequential (Sequential)     (None, 224, 224, 3)       0         
                                                                 
 tf.math.truediv (TFOpLambda  (None, 224, 224, 3)      0         
 )                                                               
                                                                 
 tf.math.subtract (TFOpLambd  (None, 224, 224, 3)      0         
 a)                                                              
                                                                 
 mobilenetv2_1.00_224 (Funct  (None, 7, 7, 1280)       2257984   
 ional)                                                          
                                                             

In [34]:
# predictions = model.predict(apple_images).flatten()
# clear predictions array
predictions = np.zeros(0)
predictions = model.predict(apple_images)
# print(predictions)
print(type(predictions))
print('Predictions:\n', predictions)
len(predictions)

3/3 [==============================] - 2s 369ms/step
<class 'numpy.ndarray'>
Predictions:
 [[1.01086780e-01 8.73134136e-01 2.40809545e-02 1.69817253e-03]
 [2.98920274e-01 3.89359534e-01 2.41827890e-02 2.87537366e-01]
 [9.59433675e-01 2.19885949e-02 1.35311568e-02 5.04650502e-03]
 [5.29243145e-04 9.93137240e-01 6.08730363e-03 2.46207113e-04]
 [4.12381142e-02 9.20280814e-01 7.54030561e-03 3.09408456e-02]
 [1.77066192e-01 7.68127561e-01 4.90039624e-02 5.80231519e-03]
 [6.43730527e-05 9.99873638e-01 3.99859600e-05 2.18771529e-05]
 [8.50800499e-02 7.50585079e-01 2.01023724e-02 1.44232541e-01]
 [7.12733194e-02 8.95985603e-01 1.87750235e-02 1.39660304e-02]
 [3.03934664e-02 9.62696820e-02 1.74531750e-02 8.55883718e-01]
 [9.94013739e-04 9.96784329e-01 1.92108902e-03 3.00467887e-04]
 [5.39367385e-02 7.89693177e-01 1.52194545e-01 4.17548697e-03]
 [1.51573669e-03 9.92922187e-01 3.38856643e-03 2.17337813e-03]
 [9.10918176e-01 3.94120347e-04 1.28890341e-03 8.73988271e-02]
 [2.34024972e-02 8.75298500

80

In [ ]:
# Output structure:

# apple 1 [p1, p2, p3, p4]
# apple 2 [p1, p2, p3, p4]
# apple 3 [p1, p2, p3, p4]

# 1. Get highest p in list + store value:

# Result:

# result 1 [2, p2]
# result 2 [1, p1]
# result 3 [3, p3]

In [45]:
prediction_labels = ['Blotch', 'Normal', 'Rot', 'Scab']

In [46]:
labels = list() 

for row in predictions:
    
    # Look at first label
    highest = row[0]
    index = 0
    
    for i in range(1, 4):
        
        if row[i] > highest:
            
            highest = row[i]
            index = i
            
    labels.append(prediction_labels[index])
    
print(labels)

['Normal', 'Normal', 'Blotch', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Scab', 'Normal', 'Normal', 'Normal', 'Blotch', 'Normal', 'Normal', 'Normal', 'Normal', 'Blotch', 'Normal', 'Rot', 'Normal', 'Blotch', 'Rot', 'Normal', 'Blotch', 'Normal', 'Normal', 'Normal', 'Blotch', 'Blotch', 'Rot', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Blotch', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Scab', 'Normal', 'Blotch', 'Blotch', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Blotch', 'Blotch', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Rot']
